# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute Euclidean distance matrix by rows
#' 
#' Used in consmx function
#' 
#' @param x A numeric matrix.
ED1 <- function(x) {
    .Call('_SC3min_ED1', PACKAGE = 'SC3min', x)
}

#' Compute Euclidean distance matrix by columns
#' 
#' Used in sc3-funcs.R distance matrix calculation
#' and within the consensus clustering.
#' 
#' @param x A numeric matrix.
ED2 <- function(x) {
    .Call('_SC3min_ED2', PACKAGE = 'SC3min', x)
}

#' Graph Laplacian calculation
#' 
#' Calculate graph Laplacian of a symmetrix matrix
#' 
#' @param A symmetric matrix
#' @export
norm_laplacian <- function(A) {
    .Call('_SC3min_norm_laplacian', PACKAGE = 'SC3min', A)
}

#' Matrix left-multiplied by its transpose
#' 
#' Given matrix A, the procedure returns A'A.
#' 
#' @param x Numeric matrix.
tmult <- function(x) {
    .Call('_SC3min_tmult', PACKAGE = 'SC3min', x)
}

